update settings, add http-parser

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -20,6 +20,18 @@ ret=$?; if [[ $ret -ne 0 ]]; then echo "build st-1.9 failed, ret=$ret"; exit $re
 if [ ! -f ${GLOBAL_DIR_OBJS}/st-1.9/obj/libst.a ]; then echo "build st-1.9 failed."; exit -1; fi
 if [ ! -f ${GLOBAL_DIR_OBJS}/st-1.9/obj/libst.so ]; then echo "build st-1.9 failed."; exit -1; fi
 
+# http-parser-2.1
+if [[ -f ${GLOBAL_DIR_OBJS}/http-parser-2.1/http_parser.h && -f ${GLOBAL_DIR_OBJS}/http-parser-2.1/libhttp_parser.a ]]; then
+    echo "http-parser-2.1 is ok.";
+else
+    echo "build http-parser-2.1";
+    (rm -rf ${GLOBAL_DIR_OBJS}/http-parser-2.1 && cd ${GLOBAL_DIR_OBJS} && unzip ../3rdparty/http-parser-2.1.zip && cd http-parser-2.1 && make package)
+fi
+# check status
+ret=$?; if [[ $ret -ne 0 ]]; then echo "build http-parser-2.1 failed, ret=$ret"; exit $ret; fi
+if [[ ! -f ${GLOBAL_DIR_OBJS}/http-parser-2.1/http_parser.h ]]; then echo "build http-parser-2.1 failed"; exit -1; fi
+if [[ ! -f ${GLOBAL_DIR_OBJS}/http-parser-2.1/libhttp_parser.a ]]; then echo "build http-parser-2.1 failed"; exit -1; fi
+
 #####################################################################################
 # generate Makefile.
 #####################################################################################
@@ -87,6 +99,8 @@ END
 # Libraries
 LibSTRoot="${GLOBAL_DIR_OBJS}/st-1.9/obj"
 LibSTfile="${LibSTRoot}/libst.a"
+LibHttpParserRoot="${GLOBAL_DIR_OBJS}/http-parser-2.1"
+LibHttpParserfile="${LibHttpParserRoot}/libhttp_parser.a"
 
 #Core Module
 MODULE_ID="CORE" 
@@ -115,7 +129,7 @@ PROTOCOL_OBJS="${MODULE_OBJS[@]}"
 #Main Module
 MODULE_ID="MAIN" 
 MODULE_DEPENDS=("CORE" "CONFIG" "PROTOCOL") 
-ModuleLibIncs=(${LibSTRoot})
+ModuleLibIncs=(${LibSTRoot} ${LibHttpParserRoot})
 MODULE_FILES=("htl_app_http_load" "htl_app_hls_load")
 MODULE_DIR="src/main" . auto/modules.sh
 MAIN_OBJS="${MODULE_OBJS[@].o}"
@@ -123,13 +137,13 @@ MAIN_OBJS="${MODULE_OBJS[@].o}"
 # all main entrances
 MAIN_ENTRANCES=("htl_app_http_load" "htl_app_hls_load")
 
-# CC Smart Server over st(state-threads)
-ModuleLibFiles=(${LibSTfile})
+# http load test tool over st(state-threads)
+ModuleLibFiles=(${LibSTfile} ${LibHttpParserfile})
 MODULE_OBJS="${CORE_OBJS[@]} ${CONFIG_OBJS[@]} ${PROTOCOL_OBJS[@]} ${MAIN_OBJS[@]}"
 BUILD_KEY="st_http_load" APP_MAIN="htl_app_http_load" APP_NAME="st_http_load" LINK_OPTIONS="-ldl" SO_PATH="" . auto/apps.sh
 
-# CC Smart Server CLI over direct TCP.
-ModuleLibFiles=()
+# hls load test tool over direct TCP.
+ModuleLibFiles=(${LibSTfile} ${LibHttpParserfile})
 MODULE_OBJS="${CORE_OBJS[@]} ${CONFIG_OBJS[@]} ${PROTOCOL_OBJS[@]} ${MAIN_OBJS[@]}"
 BUILD_KEY="st_hls_load" APP_MAIN="htl_app_hls_load" APP_NAME="st_hls_load" LINK_OPTIONS="-ldl" SO_PATH="" . auto/apps.sh
 
